#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC     = cc
#CFLAGS = -dn

ARCH = linux
CFLAGS = -std=gnu89
LDFLAGS = -lnsl -L/usr/ucblib -lcurses -lm

include ../Makefile.common
