#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

ARCH = linux
LDFLAGS = -lnsl -L/usr/ucblib -lcurses -lm

include ../Makefile.common
