#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

ARCH = linux
CFLAGS = -std=c89
LDFLAGS = -lnsl -L/usr/ucblib -lcurses -lm

include ../Makefile.common
