#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc
CFLAGS = 

ARCH = linux
LDFLAGS = -lm -lbsd

include ../Makefile.common
