#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc

ARCH = linux
CFLAGS = -std=c89
LDFLAGS = -lm -lbsd

include ../Makefile.common
