#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = cc
#CFLAGS = -dn

ARCH = linux
CFLAGS = -std=c89
LDFLAGS = -lnsl -lcurses

include ../Makefile.common
