#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc

ARCH = linux
LDFLAGS = -lnsl -lcurses

include ../Makefile.common
