#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc

ARCH = linux
CFLAGS = -std=c89
LDFLAGS = -lnsl -lcurses

include ../Makefile.common
