#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

ARCH = linux
ARCH_FLAGS = -DLINUX -D_GNU_SOURCE
CPPFLAGS = -O2 -std=gnu89


include ../Makefile.common
