#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = cc
#CFLAGS = -dn

ARCH = linux
CFLAGS = -std=gnu89
LDFLAGS = -lnsl -lcurses -lm

include ../Makefile.common
